model notebook for coding in sklearn 

In [2]:
# import the libraries 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.preprocessing import StandardScaler , LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split



In [3]:
# import data set 
df=sns.load_dataset('tips')
df.head()


total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
# sperate the features (x) and label (y) 
X=df[['total_bill']]
y=df['tip']


In [5]:
#train test split 
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.8)


In [6]:
# preprocess the dataa 
#scalar=StandardScaler()
# X_train=scalar.fit_transform(X_train)
#X_test=scalar.fit_transform(X_test)
# X_train

In [7]:
# built the model 
# train the model 
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [8]:
model.predict([[80]])

c:\Users\Public\anaconda3\envs\python_ml\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.06831693])

In [9]:
# predict the model 
y_predict=model.predict(X_test)
y_predict

array([5.88288404, 4.09490548, 2.04992382, 3.45440558, 1.79593248,
       2.54385164, 2.31094259, 2.5960554 , 5.88890755, 2.67536495,
       3.20342599, 2.31797002, 4.53361779, 2.38422863, 2.5468634 ,
       2.38422863, 2.33202488, 2.42338144, 3.09801457, 4.51554726,
       2.91530143, 3.7676281 , 3.00966975, 2.16537443, 2.78981164,
       4.02864687, 4.31777535, 3.94532165, 2.37920904, 2.24468398,
       2.49465965, 2.66432185, 2.79483123, 3.86300034, 3.28775513,
       1.34517315, 2.47357736, 2.8259527 , 2.355115  , 2.908274  ,
       3.35602158, 4.05474874, 2.46855777, 2.91329359, 3.13716738,
       3.68831855, 3.54676606, 3.07392053, 2.34206406])

In [10]:
y_test

59     6.73
187    2.00
226    2.00
119    2.92
195    1.44
69     2.09
27     2.00
234    3.00
212    9.00
93     4.30
15     3.92
209    2.23
85     5.17
224    1.58
8      1.96
221    3.48
215    1.10
163    2.00
204    4.00
180    3.68
200    4.00
77     4.00
29     3.00
58     1.76
41     2.54
125    4.20
83     5.00
90     3.00
26     2.00
97     1.50
127    2.00
162    2.00
164    3.00
216    3.00
103    3.48
67     1.00
109    4.00
242    1.75
151    2.00
146    1.36
189    4.00
210    2.00
122    2.50
38     2.31
104    4.08
57     1.50
157    3.75
21     2.75
198    2.00
Name: tip, dtype: float64

In [11]:
# evaluate the model 
from sklearn.metrics import r2_score,mean_squared_error
print('MSE:',mean_squared_error(y_test,y_predict))
print('R2:',r2_score(y_test,y_predict))



MSE: 0.9542602046947551
R2: 0.5586098517468425


save and load the model 

In [16]:
# save the model 
import pickle
pickle.dump(model,open('./saved_models/model_01.pkl','wb'))


In [13]:
# load the model 
import pickle
model_load=pickle.load(open('./saved_models/model_01.pkl','rb'))

In [15]:
model_load.predict([[300]])

c:\Users\Public\anaconda3\envs\python_ml\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([31.15452037])